name: movies_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  vector_graphics: ^1.1.11
  flutter_gen: ^5.12.0
  flutter_native_splash: ^2.4.7
  dio: ^5.4.0
  flutter_bloc: ^8.1.6 # Added Bloc

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner:
  flutter_gen_runner:
  flutter_lints: ^6.0.0

flutter_gen:
  output: lib/core/gen
  integrations:
    image: true
    flutter_svg: true

flutter_native_splash:
   web: false
   color: "#121312"
   image: assets/images/logo.png
   branding: assets/images/branding.png
   fullscreen: true
   android_12:
    color: "#121312"
    image: assets/images/logo.png
    icon_background_color: "#121312"
    branding: assets/images/branding.png

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/avatars/
    - assets/images/onboarding/
    - assets/icons/
