// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkUj_J9z7o-d-5woXQdF9HgxkYXhAaXdw',
    appId: '1:222517298739:web:00a008225d99e38b40c546',
    messagingSenderId: '222517298739',
    projectId: 'movies-app-flutter-route',
    authDomain: 'movies-app-flutter-route.firebaseapp.com',
    storageBucket: 'movies-app-flutter-route.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCK_KU6fXeued7xceR5jQf6vd_kAFSJFWM',
    appId: '1:222517298739:android:05bfb9985e69103e40c546',
    messagingSenderId: '222517298739',
    projectId: 'movies-app-flutter-route',
    storageBucket: 'movies-app-flutter-route.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0Is6kOuvnpMNi-VIbL-sguYyFhtjaLjY',
    appId: '1:222517298739:ios:29607b923874f51240c546',
    messagingSenderId: '222517298739',
    projectId: 'movies-app-flutter-route',
    storageBucket: 'movies-app-flutter-route.firebasestorage.app',
    iosBundleId: 'com.example.moviesApp',
  );

}